import { useState } from 'react'
import type { CityConfig, Report } from '../../types'
import { readinessLabel, readinessColor } from '../../data/reportStore'

interface Props {
  city: CityConfig
  readiness: number
  active: Report[]
  t: (k: string) => string
  rtl: boolean
}

type Role = 'emergency_manager' | 'hospital' | 'community_org'

const ROLES: { key: Role; label: string }[] = [
  { key: 'emergency_manager', label: 'Emergency Manager' },
  { key: 'hospital',          label: 'Hospital' },
  { key: 'community_org',     label: 'Community Org' },
]

export default function OperationalStatus({ city, readiness, active, t, rtl }: Props) {
  const [role, setRole] = useState<Role>('emergency_manager')
  const [copied, setCopied] = useState(false)

  const r = city.resources
  const color = readinessColor(readiness)
  const label = readinessLabel(readiness)
  const CIRC  = 2 * Math.PI * 38  // r=38 → circumference ≈ 238.8

  const emergencies = active.filter((rep) => rep.urgency === 'emergency').length
  const medAccess   = ((r.hospitalsOperating / Math.max(r.hospitalsTotal, 1)) * 3.5).toFixed(1)

  const briefingLines = [
    `${active.length} active reports · ${emergencies} emergency-level`,
    `Medical access: ${medAccess}/100k (WHO minimum: 1.0)`,
    `${r.corridorsPassable} of ${r.corridorsTotal} evacuation corridors confirmed passable`,
    `Supply chain estimated at ${r.supplyDays} days`,
  ]

  function handleCopy() {
    const text = [
      `RIPPLE INCIDENT BRIEFING — ${city.fullName}`,
      `Generated: ${new Date().toLocaleString()}`,
      `Humanitarian Readiness Index: ${readiness} (${label})`,
      '',
      ...briefingLines.map((l) => `• ${l}`),
      '',
      `Generated by Ripple · ripple.app · Data: OSM contributors, synthetic field reports`,
    ].join('\n')
    navigator.clipboard.writeText(text).then(() => {
      setCopied(true)
      setTimeout(() => setCopied(false), 2000)
    })
  }

  function barWidth(val: number, max: number) {
    return Math.max(0, Math.min(100, (val / Math.max(max, 1)) * 100))
  }

  const resources = [
    {
      icon: '🏥',
      label: t('dash.hospitals'),
      val: r.hospitalsOperating,
      max: r.hospitalsTotal,
      display: `${r.hospitalsOperating} of ${r.hospitalsTotal} operating`,
      danger: r.hospitalsOperating / r.hospitalsTotal < 0.4,
    },
    {
      icon: '⛺',
      label: t('dash.shelters'),
      val: r.sheltersAtCapacity,
      max: r.sheltersTotal,
      display: `${r.sheltersAtCapacity} of ${r.sheltersTotal} at capacity`,
      danger: r.sheltersAtCapacity >= r.sheltersTotal,
      inverted: true,
    },
    {
      icon: '🛣️',
      label: t('dash.corridors'),
      val: r.corridorsPassable,
      max: r.corridorsTotal,
      display: `${r.corridorsPassable} of ${r.corridorsTotal} passable`,
      danger: r.corridorsPassable / r.corridorsTotal < 0.5,
    },
    {
      icon: '🍞',
      label: t('dash.supply'),
      val: r.supplyDays,
      max: 14,
      display: `${r.supplyDays} days estimated`,
      danger: r.supplyDays < 3,
    },
  ]

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: 10 }} dir={rtl ? 'rtl' : 'ltr'}>

      {/* Card 1 — Readiness Ring */}
      <div className="glass-card" style={{ borderRadius: 20, padding: 18 }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', color: '#6b7280', textTransform: 'uppercase', marginBottom: 14 }}>
          {t('dash.readiness')}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center' }}>
          <svg width="130" height="130" viewBox="0 0 84 84">
            <circle cx="42" cy="42" r="38" fill="none" stroke="#e8e8e8" strokeWidth="8" />
            <circle
              cx="42" cy="42" r="38"
              fill="none"
              stroke={color}
              strokeWidth="8"
              strokeDasharray={`${(readiness / 100) * CIRC} ${CIRC}`}
              strokeLinecap="round"
              transform="rotate(-90 42 42)"
              style={{ transition: 'stroke-dasharray 0.6s ease-out, stroke 0.4s ease' }}
            />
            <text x="42" y="39" textAnchor="middle" dominantBaseline="middle"
              fontSize="22" fontWeight="800" fill={color}
              style={{ fontVariantNumeric: 'tabular-nums', transition: 'fill 0.4s' }}>
              {readiness}
            </text>
            <text x="42" y="56" textAnchor="middle" dominantBaseline="middle"
              fontSize="7" fontWeight="700" fill={color} letterSpacing="1.5">
              {label}
            </text>
          </svg>
          <div style={{ fontSize: 9, fontWeight: 600, letterSpacing: '0.15em', color: '#9ca3af', textTransform: 'uppercase', marginTop: 4 }}>
            HUMANITARIAN READINESS INDEX
          </div>
          <div style={{ fontSize: 10, color: '#9ca3af', marginTop: 2 }}>
            Field report data · illustrative
          </div>
        </div>
      </div>

      {/* Card 2 — Resources */}
      <div className="glass-card" style={{ borderRadius: 20, padding: 18 }}>
        <div style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', color: '#6b7280', textTransform: 'uppercase', marginBottom: 14 }}>
          {t('dash.resources')}
        </div>
        <div style={{ display: 'flex', flexDirection: 'column', gap: 12 }}>
          {resources.map((res) => {
            const width = res.inverted
              ? barWidth(res.max - res.val, res.max)
              : barWidth(res.val, res.max)
            const barColor = res.danger ? '#e05252' : '#3d8b85'
            return (
              <div key={res.label}>
                <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                  <span style={{ fontSize: 12, fontWeight: 500, color: '#1a2734', display: 'flex', alignItems: 'center', gap: 5 }}>
                    {res.icon} {res.label}
                  </span>
                  <span style={{ fontSize: 11, color: res.danger ? '#e05252' : '#4b5563', fontWeight: res.danger ? 700 : 400 }}>
                    {res.display}
                  </span>
                </div>
                <div style={{ height: 6, background: '#e5e7eb', borderRadius: 6, overflow: 'hidden' }}>
                  <div style={{
                    height: '100%', width: `${width}%`,
                    background: barColor, borderRadius: 6,
                    transition: 'width 0.4s ease-out',
                  }} />
                </div>
              </div>
            )
          })}
        </div>
      </div>

      {/* Card 3 — Incident Briefing */}
      <div className="glass-card" style={{ borderRadius: 20, padding: 18 }}>
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 12 }}>
          <span style={{ fontSize: 10, fontWeight: 700, letterSpacing: '0.15em', color: '#6b7280', textTransform: 'uppercase' }}>
            {t('dash.briefing')}
          </span>
          <button onClick={handleCopy} style={{
            fontSize: 11, fontWeight: 600, cursor: 'pointer',
            background: copied ? '#3d8b85' : 'rgba(255,255,255,0.6)',
            color: copied ? '#fff' : '#1a2734',
            border: '1px solid rgba(0,0,0,0.1)',
            borderRadius: 8, padding: '4px 10px',
            transition: 'all 0.2s',
          }}>
            {copied ? t('dash.copied') : t('dash.copy')}
          </button>
        </div>

        {/* Role pills */}
        <div style={{ display: 'flex', gap: 4, marginBottom: 12, flexWrap: 'wrap' }}>
          {ROLES.map(({ key, label: rl }) => (
            <button key={key} onClick={() => setRole(key)} style={{
              fontSize: 11, fontWeight: 600, cursor: 'pointer',
              padding: '4px 10px', borderRadius: 20,
              background: role === key ? '#3d8b85' : 'rgba(255,255,255,0.5)',
              border: role === key ? '1px solid #3d8b85' : '1px solid rgba(0,0,0,0.1)',
              color: role === key ? '#fff' : '#4b5563',
            }}>
              {rl}
            </button>
          ))}
        </div>

        {/* Briefing bullets */}
        <div style={{ display: 'flex', flexDirection: 'column', gap: 7 }}>
          {briefingLines.map((line, i) => (
            <div key={i} style={{ display: 'flex', gap: 8, fontSize: 12, color: '#1a2734', lineHeight: 1.4 }}>
              <span style={{ color: '#3d8b85', fontWeight: 700, flexShrink: 0 }}>●</span>
              <span>{line}</span>
            </div>
          ))}
        </div>
      </div>
    </div>
  )
}
